port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback: []
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP
proxies:
  - name: "Traffic: 19.33 GB | 100 GB"
    server: gzbgp01.00991169.xyz
    port: 14901
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: "Expire: 2022-12-28"
    server: gzbgp01.00991169.xyz
    port: 14901
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-01
    server: gzbgp01.00991169.xyz
    port: 14901
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-02
    server: gzbgp01.00991169.xyz
    port: 14902
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-03
    server: gzbgp01.00991169.xyz
    port: 14903
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-04
    server: gzbgp01.00991169.xyz
    port: 14904
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-05
    server: gzbgp01.00991169.xyz
    port: 14905
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯-06
    server: gzbgp01.00991169.xyz
    port: 14906
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-01
    server: shbgp01.00991169.xyz
    port: 14931
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-02
    server: shbgp01.00991169.xyz
    port: 14932
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-03
    server: shbgp01.00991169.xyz
    port: 14933
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬-04
    server: shbgp01.00991169.xyz
    port: 14934
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-01
    server: gzbgp01.00991169.xyz
    port: 14941
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-02
    server: gzbgp01.00991169.xyz
    port: 14942
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸ-03
    server: gzbgp01.00991169.xyz
    port: 14943
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-01
    server: shbgp01.00991169.xyz
    port: 14911
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-02
    server: shbgp01.00991169.xyz
    port: 14912
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-03
    server: shbgp01.00991169.xyz
    port: 14913
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-04
    server: shbgp01.00991169.xyz
    port: 14914
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-05
    server: shbgp01.00991169.xyz
    port: 14915
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡ºğŸ‡¸ ç¾å›½-06
    server: shbgp01.00991169.xyz
    port: 14916
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾-01
    server: gzbgp01.00991169.xyz
    port: 14951
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡°ğŸ‡· éŸ©å›½-01
    server: shbgp01.00991169.xyz
    port: 14965
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡°ğŸ‡· éŸ©å›½-02
    server: shbgp01.00991169.xyz
    port: 14966
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡®ğŸ‡³ å°åº¦-01
    server: gzbgp01.00991169.xyz
    port: 14921
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¹ğŸ‡­ æ³°å›½-01
    server: gzbgp01.00991169.xyz
    port: 14961
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡»ğŸ‡³ è¶Šå—-01
    server: gzbgp01.00991169.xyz
    port: 14962
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¦ğŸ‡º æ‚‰å°¼-01
    server: gzbgp01.00991169.xyz
    port: 14970
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¦ğŸ‡ª è¿ªæ‹œ-01
    server: gzbgp01.00991169.xyz
    port: 14972
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¬ğŸ‡§ ä¼¦æ•¦-01
    server: bjbgp01.00991169.xyz
    port: 14963
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¬ğŸ‡§ ä¼¦æ•¦-02
    server: bjbgp01.00991169.xyz
    port: 14964
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
  - name: ğŸ‡¹ğŸ‡· åœŸè€³å…¶-01
    server: bjbgp01.00991169.xyz
    port: 14971
    type: trojan
    password: C4E49C72-F993-7150-42E1-CF1D0C363E30
    sni: iqiyi.com
    skip-cert-verify: true
    udp: true
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - HK
      - JP
      - SG
      - TW
      - US
      - "Traffic: 19.33 GB | 100 GB"
      - "Expire: 2022-12-28"
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-02
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-03
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-04
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-05
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-06
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-02
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-03
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-04
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-01
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-02
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-03
      - ğŸ‡ºğŸ‡¸ ç¾å›½-01
      - ğŸ‡ºğŸ‡¸ ç¾å›½-02
      - ğŸ‡ºğŸ‡¸ ç¾å›½-03
      - ğŸ‡ºğŸ‡¸ ç¾å›½-04
      - ğŸ‡ºğŸ‡¸ ç¾å›½-05
      - ğŸ‡ºğŸ‡¸ ç¾å›½-06
      - ğŸ‡¨ğŸ‡³ å°æ¹¾-01
      - ğŸ‡°ğŸ‡· éŸ©å›½-01
      - ğŸ‡°ğŸ‡· éŸ©å›½-02
      - ğŸ‡®ğŸ‡³ å°åº¦-01
      - ğŸ‡¹ğŸ‡­ æ³°å›½-01
      - ğŸ‡»ğŸ‡³ è¶Šå—-01
      - ğŸ‡¦ğŸ‡º æ‚‰å°¼-01
      - ğŸ‡¦ğŸ‡ª è¿ªæ‹œ-01
      - ğŸ‡¬ğŸ‡§ ä¼¦æ•¦-01
      - ğŸ‡¬ğŸ‡§ ä¼¦æ•¦-02
      - ğŸ‡¹ğŸ‡· åœŸè€³å…¶-01
  - name: Netflix
    type: select
    proxies:
      - Proxies
      - HK
      - JP
      - SG
      - TW
      - US
  - name: Streaming
    type: select
    proxies:
      - Proxies
      - HK
      - JP
      - SG
      - TW
      - US
  - name: StreamingSE
    type: select
    proxies:
      - DIRECT
      - HK
      - TW
  - name: HK
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-01
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-02
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-03
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-04
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-05
      - ğŸ‡­ğŸ‡° é¦™æ¸¯-06
  - name: JP
    type: select
    proxies:
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-01
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-02
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-03
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬-04
  - name: SG
    type: select
    proxies:
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-01
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-02
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸ-03
  - name: TW
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ å°æ¹¾-01
  - name: US
    type: select
    proxies:
      - ğŸ‡ºğŸ‡¸ ç¾å›½-01
      - ğŸ‡ºğŸ‡¸ ç¾å›½-02
      - ğŸ‡ºğŸ‡¸ ç¾å›½-03
      - ğŸ‡ºğŸ‡¸ ç¾å›½-04
      - ğŸ‡ºğŸ‡¸ ç¾å›½-05
      - ğŸ‡ºğŸ‡¸ ç¾å›½-06
rules:
  - DOMAIN-KEYWORD, gitee, DIRECT
  - DOMAIN-KEYWORD, programmercarl, DIRECT
  - DOMAIN-KEYWORD, spring.io, Proxies
  - DOMAIN-KEYWORD, openai.com, Proxies
  - DOMAIN-KEYWORD, grammarly, Proxies
  - DOMAIN-KEYWORD, txl.ca, Proxies
  - DOMAIN-KEYWORD, mo.fish, Proxies
  - DOMAIN-KEYWORD, deeply, Proxies
  - DOMAIN-KEYWORD, google, Proxies
  - DOMAIN-KEYWORD, overleaf.com, Proxies
  - DOMAIN-KEYWORD, git, Proxies
  - DOMAIN-KEYWORD, github, Proxies
  - RULE-SET,applications,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,Proxies
  - RULE-SET,apple,Proxies
  - RULE-SET,google,Proxies
  - RULE-SET,proxy,Proxies
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - RULE-SET,telegramcidr,Proxies
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxies
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
rule-providers:
  reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
    interval: 86400
  icloud:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
    interval: 86400
  apple:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
    interval: 86400
  google:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: ./ruleset/google.yaml
    interval: 86400
  proxy:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
    interval: 86400
  direct:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
    interval: 86400
  private:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
    interval: 86400
  gfw:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
    interval: 86400
  greatfire:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
    interval: 86400
  tld-not-cn:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400
  telegramcidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
    interval: 86400
  cncidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
    interval: 86400
  lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
    interval: 86400
  applications:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
    interval: 86400
